[default.extend-words]
Bord = "Bord"
Tableau = "Tableau"
EtherVox = "EtherVox"
Enregistrement = "Enregistrement"
Etat = "Etat"
État = "État"
Confidentialité = "Confidentialité"
Paramètres = "Paramètres"
